const actions = {
  FETCH_DATA_START: 'FETCH_DATA_START',
  FETCH_DATA_SUCSSES: 'FETCH_DATA_SUCSSES',
  FETCH_DATA_LOADING: 'FETCH_DATA_LOADING',
  FETCH_DATA_FAILED: 'FETCH_DATA_FAILED',
  AUTOCOMPLETE_START: 'AUTOCOMPLETE_START',
  AUTOCOMPLETE_SUCSSES: 'AUTOCOMPLETE_SUCSSES',
  AUTOCOMPLETE_LOADING: 'AUTOCOMPLETE_LOADING',
  AUTOCOMPLETE_FAILED: 'AUTOCOMPLETE_FAILED',
  FETCH_FORECAST_SUCSSES: 'FETCH_FORECAST_SUCSSES',
}

export default actions
